OrdererOrgs:
  - Name: Orderer
    Domain: stockchainz.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Market1
    Domain: market1.stockchainz.com
    EnableNodeOUs: true
    Template:
      Count: 1

  - Name: Market2
    Domain: market2.stockchainz.com
    EnableNodeOUs: true
    Template:
      Count: 1
      
  - Name: Market3
    Domain: market3.stockchainz.com
    EnableNodeOUs: true
    Template:
      Count: 1
